import { Ionicons } from '@expo/vector-icons';

export type ServiceBadge = 'Popular' | 'Best value' | 'New' | 'Top rated';

export interface ServiceItem {
  id: string;
  name: string;
  price: string;
  rating: string;
  reviews: string;
  icon: keyof typeof Ionicons.glyphMap;
  tint: string;
  duration?: string;
  location?: string;
  category: string;
  desc?: string;
  badge?: ServiceBadge;
  perks?: string[];
}

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: 'apps-outline' as const },
  { id: 'packages', label: 'Packages', icon: 'cube-outline' as const },
  { id: 'deep', label: 'Deep', icon: 'home-outline' as const },
  { id: 'regular', label: 'Regular', icon: 'sparkles-outline' as const },
  { id: 'kitchen', label: 'Kitchen', icon: 'restaurant-outline' as const },
  { id: 'bathroom', label: 'Bathroom', icon: 'water-outline' as const },
  { id: 'appliance', label: 'Appliance', icon: 'build-outline' as const },
  { id: 'outdoor', label: 'Outdoor', icon: 'sunny-outline' as const },
  { id: 'specialty', label: 'Specialty', icon: 'star-outline' as const },
];

export const HOME_SERVICES: ServiceItem[] = [
  {
    id: 'deep',
    name: 'Deep Cleaning',
    price: '₹499',
    rating: '4.85',
    reviews: '12k',
    icon: 'home-outline',
    tint: '#E6F4F2',
    duration: '3–4 hrs',
    location: 'Raipur',
    category: 'deep',
    desc: 'Full home deep clean — every corner',
    badge: 'Popular',
    perks: ['All rooms', 'Inside cabinets', 'Balcony mop'],
  },
  {
    id: 'regular',
    name: 'Regular Cleaning',
    price: '₹149',
    rating: '4.82',
    reviews: '28k',
    icon: 'sparkles-outline',
    tint: '#EEF6FF',
    duration: '1–2 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Weekly maintenance for busy homes',
    badge: 'Best value',
    perks: ['Dusting', 'Mopping', 'Bathroom wipe'],
  },
  {
    id: 'kitchen',
    name: 'Kitchen Cleaning',
    price: '₹299',
    rating: '4.80',
    reviews: '8k',
    icon: 'restaurant-outline',
    tint: '#FFF8EE',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'kitchen',
    desc: 'Degrease chimney, slabs & appliances',
    badge: 'Top rated',
    perks: ['Chimney wipe', 'Slab polish', 'Sink shine'],
  },
  {
    id: 'bathroom',
    name: 'Bathroom Cleaning',
    price: '₹199',
    rating: '4.78',
    reviews: '6k',
    icon: 'water-outline',
    tint: '#F3EEFF',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'bathroom',
    desc: 'Tiles, taps, fittings & floor scrub',
    perks: ['Anti-fungal', 'Tap descale', 'Mirror polish'],
  },
  {
    id: 'sofa',
    name: 'Sofa & Upholstery',
    price: '₹349',
    rating: '4.81',
    reviews: '4k',
    icon: 'bed-outline',
    tint: '#FFF0F6',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Shampoo, vacuum & stain treatment',
    perks: ['Fabric safe', 'Odor removal', 'Cushion dry'],
  },
  {
    id: 'mattress',
    name: 'Mattress Cleaning',
    price: '₹399',
    rating: '4.79',
    reviews: '3k',
    icon: 'layers-outline',
    tint: '#F0F9FF',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Dust mites, stains & deep vacuum',
    perks: ['UV sanitize', 'Both sides', 'Quick dry'],
  },
  {
    id: 'window',
    name: 'Window & Glass',
    price: '₹249',
    rating: '4.77',
    reviews: '2k',
    icon: 'scan-outline',
    tint: '#ECFEFF',
    duration: '1–2 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Streak-free glass inside & out',
    perks: ['Frame wipe', 'Grill dusting', 'No streaks'],
  },
  {
    id: 'balcony',
    name: 'Balcony Cleaning',
    price: '₹179',
    rating: '4.76',
    reviews: '2k',
    icon: 'leaf-outline',
    tint: '#F0FDF4',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'Sweep, mop, railing & planter area',
    perks: ['Drain clear', 'Railing wipe', 'Floor mop'],
  },
  {
    id: 'movein',
    name: 'Move-in / Move-out',
    price: '₹899',
    rating: '4.84',
    reviews: '5k',
    icon: 'cube-outline',
    tint: '#FEF3C7',
    duration: '4–5 hrs',
    location: 'Raipur',
    category: 'deep',
    desc: 'Empty home inspection-ready clean',
    badge: 'Popular',
    perks: ['Full scrub', 'Cupboards', 'Bathroom deep'],
  },
  {
    id: 'ac',
    name: 'AC Filter & Fins',
    price: '₹279',
    rating: '4.75',
    reviews: '3k',
    icon: 'snow-outline',
    tint: '#E0F2FE',
    duration: '1 hr',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Filter wash, fin dust & cooling check',
    perks: ['Filter wash', 'Water tray', 'Basic service'],
  },
  {
    id: 'ironing',
    name: 'Iron & Fold',
    price: '₹129',
    rating: '4.74',
    reviews: '1k',
    icon: 'shirt-outline',
    tint: '#FAF5FF',
    duration: '1–2 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Clothes pressed, folded & sorted',
    perks: ['Steam press', 'Neat stacks', 'Wardrobe sort'],
  },
  {
    id: 'cobweb',
    name: 'Ceiling Cobweb Clean',
    price: '₹159',
    rating: '4.73',
    reviews: '1k',
    icon: 'planet-outline',
    tint: '#F4F6F8',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'Corners, fans & ceiling edges',
    perks: ['Fan blades', 'Corners', 'Lights dust'],
  },
  {
    id: 'fan',
    name: 'Fan & Chimney',
    price: '₹229',
    rating: '4.72',
    reviews: '2k',
    icon: 'aperture-outline',
    tint: '#FFF7ED',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Ceiling fan blades & chimney grease',
    perks: ['Blade wash', 'Motor dust', 'Hood degrease'],
  },
  {
    id: 'fridge',
    name: 'Refrigerator Clean',
    price: '₹199',
    rating: '4.71',
    reviews: '1k',
    icon: 'snow-outline',
    tint: '#F0FDFA',
    duration: '1 hr',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Defrost trays, shelves & door seals',
    perks: ['Inside-out', 'Odor removal', 'Seal wipe'],
  },
  {
    id: 'dining',
    name: 'Dining & Living',
    price: '₹219',
    rating: '4.70',
    reviews: '2k',
    icon: 'tv-outline',
    tint: '#FDF4FF',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Furniture dust, floor & decor wipe',
    perks: ['TV unit', 'Sofa dust', 'Center table'],
  },
  {
    id: 'wardrobe',
    name: 'Wardrobe Organize',
    price: '₹189',
    rating: '4.69',
    reviews: '900',
    icon: 'file-tray-stacked-outline',
    tint: '#EFF6FF',
    duration: '1–2 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Sort, wipe shelves & vacuum base',
    perks: ['Shelf wipe', 'Clothes sort', 'Pest check'],
  },
  {
    id: 'floor',
    name: 'Floor Scrub & Polish',
    price: '₹269',
    rating: '4.68',
    reviews: '1k',
    icon: 'grid-outline',
    tint: '#ECFDF5',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'deep',
    desc: 'Marble, tile & granite machine scrub',
    perks: ['Machine scrub', 'Stain lift', 'Anti-slip'],
  },
  {
    id: 'carpet',
    name: 'Carpet Shampoo',
    price: '₹319',
    rating: '4.67',
    reviews: '800',
    icon: 'resize-outline',
    tint: '#FEF2F2',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Deep shampoo for rugs & carpets',
    perks: ['Stain treat', 'Quick dry', 'Fiber safe'],
  },
  {
    id: 'office',
    name: 'Home Office Clean',
    price: '₹169',
    rating: '4.66',
    reviews: '700',
    icon: 'laptop-outline',
    tint: '#F8FAFC',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'Desk, chair, wires & screen wipe',
    badge: 'New',
    perks: ['Cable tidy', 'Screen safe', 'Chair vacuum'],
  },
  {
    id: 'postparty',
    name: 'Post-party Cleanup',
    price: '₹449',
    rating: '4.65',
    reviews: '600',
    icon: 'beer-outline',
    tint: '#FFFBEB',
    duration: '2–3 hrs',
    location: 'Raipur',
    category: 'deep',
    desc: 'Dishes, trash, floor & furniture reset',
    perks: ['Trash out', 'Floor mop', 'Furniture wipe'],
  },
  {
    id: 'laundry',
    name: 'Laundry Wash & Fold',
    price: '₹199',
    rating: '4.64',
    reviews: '1k',
    icon: 'water-outline',
    tint: '#E0E7FF',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Wash, dry fold & basic ironing',
    perks: ['Separate loads', 'Neat fold', 'Same day'],
  },
  {
    id: 'disinfection',
    name: 'Home Disinfection',
    price: '₹349',
    rating: '4.63',
    reviews: '900',
    icon: 'medkit-outline',
    tint: '#DCFCE7',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'WHO-grade spray for high-touch zones',
    perks: ['Doors & handles', 'Kid safe', 'Kitchen tops'],
  },
  {
    id: 'puja',
    name: 'Puja Room Clean',
    price: '₹149',
    rating: '4.62',
    reviews: '500',
    icon: 'flower-outline',
    tint: '#FFF1F2',
    duration: '1 hr',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Idols wipe, diya area & floor mop',
    perks: ['Gentle wipe', 'Incense ash', 'Shelf dust'],
  },
  {
    id: 'tank',
    name: 'Water Tank Area',
    price: '₹179',
    rating: '4.61',
    reviews: '400',
    icon: 'beaker-outline',
    tint: '#CFFAFE',
    duration: '1 hr',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Terrace tank surround & pipe dusting',
    perks: ['Terrace sweep', 'Pipe wipe', 'Algae scrub'],
  },
  // ── Home packages ──
  {
    id: 'bhk1deep',
    name: '1BHK Deep Clean Package',
    price: '₹799',
    rating: '4.86',
    reviews: '9k',
    icon: 'home-outline',
    tint: '#E6F4F2',
    duration: '4–5 hrs',
    location: 'Raipur',
    category: 'packages',
    desc: 'Full 1BHK — all rooms, kitchen & bathroom',
    badge: 'Popular',
    perks: ['Living + bed', 'Kitchen', 'Bathroom deep'],
  },
  {
    id: 'bhk2deep',
    name: '2BHK Deep Clean Package',
    price: '₹1,199',
    rating: '4.85',
    reviews: '7k',
    icon: 'home-outline',
    tint: '#DCFCE7',
    duration: '5–6 hrs',
    location: 'Raipur',
    category: 'packages',
    desc: 'Complete 2BHK deep clean with balcony',
    badge: 'Top rated',
    perks: ['2 bedrooms', 'Hall + kitchen', '2 bathrooms'],
  },
  {
    id: 'bhk3deep',
    name: '3BHK Deep Clean Package',
    price: '₹1,599',
    rating: '4.84',
    reviews: '4k',
    icon: 'home-outline',
    tint: '#E0F2FE',
    duration: '6–8 hrs',
    location: 'Raipur',
    category: 'packages',
    desc: 'Large home full deep clean with extras',
    perks: ['All rooms', 'Balcony', 'Utility area'],
  },
  {
    id: 'bhk1regular',
    name: '1BHK Regular Clean',
    price: '₹249',
    rating: '4.83',
    reviews: '11k',
    icon: 'sparkles-outline',
    tint: '#EEF6FF',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'packages',
    desc: 'Weekly upkeep for 1BHK homes',
    badge: 'Best value',
    perks: ['Dust & mop', 'Bathroom wipe', 'Kitchen surface'],
  },
  {
    id: 'bhk2regular',
    name: '2BHK Regular Clean',
    price: '₹349',
    rating: '4.82',
    reviews: '8k',
    icon: 'sparkles-outline',
    tint: '#F0F9FF',
    duration: '2–3 hrs',
    location: 'Raipur',
    category: 'packages',
    desc: 'Weekly upkeep for 2BHK homes',
    perks: ['All rooms', 'Bathroom', 'Kitchen wipe'],
  },
  // ── Room-wise ──
  {
    id: 'bedroom',
    name: 'Bedroom Deep Dust',
    price: '₹169',
    rating: '4.72',
    reviews: '3k',
    icon: 'bed-outline',
    tint: '#FAF5FF',
    duration: '1–1.5 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Bed, wardrobe exterior, floor & fans',
    perks: ['Bed making', 'Wardrobe wipe', 'Fan dust'],
  },
  {
    id: 'kidsroom',
    name: 'Kids Room Clean',
    price: '₹189',
    rating: '4.71',
    reviews: '2k',
    icon: 'happy-outline',
    tint: '#FFF7ED',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'regular',
    desc: 'Toy area, study desk & safe surface wipe',
    perks: ['Toy tidy', 'Desk wipe', 'Floor sanitize'],
  },
  {
    id: 'study',
    name: 'Study Room Clean',
    price: '₹149',
    rating: '4.70',
    reviews: '1k',
    icon: 'book-outline',
    tint: '#F8FAFC',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'Bookshelf, desk, chair & floor mop',
    perks: ['Shelf dust', 'Cable tidy', 'Chair vacuum'],
  },
  {
    id: 'hall',
    name: 'Hall & Passage Clean',
    price: '₹159',
    rating: '4.69',
    reviews: '2k',
    icon: 'enter-outline',
    tint: '#F1F5F9',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'Entry, passage, shoe area & decor dust',
    perks: ['Shoe rack', 'Door wipe', 'Floor mop'],
  },
  // ── Kitchen extras ──
  {
    id: 'chimney',
    name: 'Chimney Deep Degrease',
    price: '₹349',
    rating: '4.74',
    reviews: '3k',
    icon: 'cloud-outline',
    tint: '#FFF8EE',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'kitchen',
    desc: 'Hood, filter & chimney grease removal',
    badge: 'Popular',
    perks: ['Filter soak', 'Hood degrease', 'Motor dust'],
  },
  {
    id: 'microwave',
    name: 'Microwave & OTG Clean',
    price: '₹129',
    rating: '4.68',
    reviews: '900',
    icon: 'radio-outline',
    tint: '#FEF3C7',
    duration: '45 min',
    location: 'Raipur',
    category: 'kitchen',
    desc: 'Inside-out wipe & odor removal',
    perks: ['Tray wash', 'Interior scrub', 'Exterior polish'],
  },
  {
    id: 'utensils',
    name: 'Utensils Scrubbing',
    price: '₹99',
    rating: '4.67',
    reviews: '2k',
    icon: 'cafe-outline',
    tint: '#FFFBEB',
    duration: '1 hr',
    location: 'Raipur',
    category: 'kitchen',
    desc: 'Sink piled utensils scrubbed & stacked',
    perks: ['Steel scrub', 'Sink clean', 'Neat stack'],
  },
  {
    id: 'slab',
    name: 'Slab & Tile Degrease',
    price: '₹179',
    rating: '4.66',
    reviews: '1k',
    icon: 'grid-outline',
    tint: '#F0FDF4',
    duration: '1 hr',
    location: 'Raipur',
    category: 'kitchen',
    desc: 'Countertop, backsplash & tile scrub',
    perks: ['Oil stain lift', 'Grout wipe', 'Polish finish'],
  },
  // ── Bathroom extras ──
  {
    id: 'toilet',
    name: 'Toilet Deep Sanitize',
    price: '₹149',
    rating: '4.73',
    reviews: '2k',
    icon: 'medical-outline',
    tint: '#F3EEFF',
    duration: '45 min',
    location: 'Raipur',
    category: 'bathroom',
    desc: 'Bowl, seat, flush & floor disinfect',
    perks: ['Anti-germ', 'Stain lift', 'Fresh scent'],
  },
  {
    id: 'showerglass',
    name: 'Shower Glass Descale',
    price: '₹179',
    rating: '4.72',
    reviews: '800',
    icon: 'water-outline',
    tint: '#ECFEFF',
    duration: '1 hr',
    location: 'Raipur',
    category: 'bathroom',
    desc: 'Hard water stains on glass & fittings',
    perks: ['Lime scale', 'Tap polish', 'No streaks'],
  },
  {
    id: 'bathfan',
    name: 'Bathroom Exhaust Fan',
    price: '₹99',
    rating: '4.65',
    reviews: '600',
    icon: 'aperture-outline',
    tint: '#F5F3FF',
    duration: '30 min',
    location: 'Raipur',
    category: 'bathroom',
    desc: 'Fan blade wash & grill dust removal',
    perks: ['Blade wash', 'Grill wipe', 'Motor dust'],
  },
  // ── Appliance extras ──
  {
    id: 'washingmachine',
    name: 'Washing Machine Clean',
    price: '₹249',
    rating: '4.70',
    reviews: '1k',
    icon: 'reload-outline',
    tint: '#E0E7FF',
    duration: '1 hr',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Drum, detergent tray & outer body',
    perks: ['Drum descale', 'Tray wash', 'Lint check'],
  },
  {
    id: 'geyser',
    name: 'Geyser & Purifier Wipe',
    price: '₹149',
    rating: '4.64',
    reviews: '700',
    icon: 'thermometer-outline',
    tint: '#FEE2E2',
    duration: '45 min',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Outer body, pipes & purifier surface',
    perks: ['Dust removal', 'Pipe wipe', 'Safe clean'],
  },
  {
    id: 'cooler',
    name: 'Desert Cooler Service',
    price: '₹199',
    rating: '4.63',
    reviews: '900',
    icon: 'snow-outline',
    tint: '#DBEAFE',
    duration: '1 hr',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Pad wash, tank & body dust before summer',
    perks: ['Pad rinse', 'Tank scrub', 'Fan dust'],
  },
  {
    id: 'purifier',
    name: 'RO Purifier Surface',
    price: '₹129',
    rating: '4.62',
    reviews: '500',
    icon: 'funnel-outline',
    tint: '#CCFBF1',
    duration: '30 min',
    location: 'Raipur',
    category: 'appliance',
    desc: 'Unit wipe, drip tray & area mop',
    perks: ['Body wipe', 'Tray clean', 'Area mop'],
  },
  // ── Outdoor ──
  {
    id: 'terrace',
    name: 'Terrace & Roof Wash',
    price: '₹299',
    rating: '4.68',
    reviews: '1k',
    icon: 'sunny-outline',
    tint: '#FEF9C3',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'outdoor',
    desc: 'Terrace sweep, mop & drain clearing',
    perks: ['Drain clear', 'Floor wash', 'Railing wipe'],
  },
  {
    id: 'garage',
    name: 'Garage / Parking Sweep',
    price: '₹199',
    rating: '4.66',
    reviews: '600',
    icon: 'car-outline',
    tint: '#F4F4F5',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'outdoor',
    desc: 'Parking area sweep, cobweb & dust',
    perks: ['Full sweep', 'Cobweb', 'Corner dust'],
  },
  {
    id: 'garden',
    name: 'Garden & Yard Sweep',
    price: '₹179',
    rating: '4.65',
    reviews: '400',
    icon: 'leaf-outline',
    tint: '#DCFCE7',
    duration: '1 hr',
    location: 'Raipur',
    category: 'outdoor',
    desc: 'Dry leaves, pathway & patio sweep',
    perks: ['Leaf clear', 'Pathway', 'Patio mop'],
  },
  {
    id: 'stairwell',
    name: 'Staircase Wash',
    price: '₹229',
    rating: '4.64',
    reviews: '350',
    icon: 'trending-up-outline',
    tint: '#E2E8F0',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'outdoor',
    desc: 'Society stairs, railing & landing mop',
    perks: ['Step scrub', 'Railing', 'Landing mop'],
  },
  // ── Specialty & festival ──
  {
    id: 'diwali',
    name: 'Pre-festival Deep Clean',
    price: '₹599',
    rating: '4.80',
    reviews: '3k',
    icon: 'flame-outline',
    tint: '#FFF4ED',
    duration: '4 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Diwali / festival ready full home scrub',
    badge: 'Popular',
    perks: ['All rooms', 'Kitchen shine', 'Entrance decor'],
  },
  {
    id: 'construction',
    name: 'Post-construction Dust',
    price: '₹999',
    rating: '4.78',
    reviews: '2k',
    icon: 'hammer-outline',
    tint: '#FEF3C7',
    duration: '6–8 hrs',
    location: 'Raipur',
    category: 'deep',
    desc: 'Renovation dust, paint marks & debris',
    perks: ['Fine dust', 'Window wipe', 'Floor scrub'],
  },
  {
    id: 'marble',
    name: 'Marble & Granite Polish',
    price: '₹449',
    rating: '4.76',
    reviews: '1k',
    icon: 'diamond-outline',
    tint: '#F8FAFC',
    duration: '2–3 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Floor machine polish for stone surfaces',
    perks: ['Machine polish', 'Stain care', 'Slip-safe'],
  },
  {
    id: 'curtain',
    name: 'Curtain Wipe & Dust',
    price: '₹279',
    rating: '4.75',
    reviews: '800',
    icon: 'albums-outline',
    tint: '#FDF2F8',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'In-place curtain dust & rod wipe',
    perks: ['Rod wipe', 'Fabric dust', 'Window ledge'],
  },
  {
    id: 'mould',
    name: 'Bathroom Mould Treatment',
    price: '₹249',
    rating: '4.74',
    reviews: '600',
    icon: 'bug-outline',
    tint: '#EDE9FE',
    duration: '1.5 hrs',
    location: 'Raipur',
    category: 'bathroom',
    desc: 'Grout mould, corners & ceiling edges',
    perks: ['Anti-fungal', 'Grout scrub', 'Seal wipe'],
  },
  {
    id: 'pestprep',
    name: 'Pest Control Prep Clean',
    price: '₹299',
    rating: '4.73',
    reviews: '500',
    icon: 'shield-outline',
    tint: '#ECFDF5',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Pre-spray kitchen & storage clearing',
    perks: ['Cabinet clear', 'Floor mop', 'Food safe'],
  },
  {
    id: 'sofa3plus',
    name: 'Sofa 3+2 Package',
    price: '₹599',
    rating: '4.77',
    reviews: '2k',
    icon: 'bed-outline',
    tint: '#FFF0F6',
    duration: '3 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Full living room sofa set shampoo',
    perks: ['3+2 seater', 'Stain treat', 'Quick dry'],
  },
  {
    id: 'mattressdouble',
    name: 'Double Mattress Clean',
    price: '₹549',
    rating: '4.76',
    reviews: '1k',
    icon: 'layers-outline',
    tint: '#F0F9FF',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'King/queen mattress both sides vacuum',
    perks: ['Both sides', 'UV care', 'Stain lift'],
  },
  {
    id: 'tvunit',
    name: 'TV Unit & Entertainment',
    price: '₹149',
    rating: '4.68',
    reviews: '900',
    icon: 'tv-outline',
    tint: '#F1F5F9',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'TV unit, set-top box area & wires',
    perks: ['Dust safe', 'Cable tidy', 'Screen wipe'],
  },
  {
    id: 'bookshelf',
    name: 'Bookshelf & Storage',
    price: '₹149',
    rating: '4.67',
    reviews: '700',
    icon: 'library-outline',
    tint: '#FFFBEB',
    duration: '1 hr',
    location: 'Raipur',
    category: 'regular',
    desc: 'Shelves, cabinets & display dusting',
    perks: ['Shelf wipe', 'Item dust', 'Base mop'],
  },
  {
    id: 'shoerack',
    name: 'Shoe Rack Organize',
    price: '₹129',
    rating: '4.66',
    reviews: '600',
    icon: 'footsteps-outline',
    tint: '#F4F4F5',
    duration: '45 min',
    location: 'Raipur',
    category: 'regular',
    desc: 'Sort, wipe & sanitize shoe storage',
    perks: ['Sort pairs', 'Rack wipe', 'Odor care'],
  },
  {
    id: 'petfriendly',
    name: 'Pet-friendly Home Clean',
    price: '₹399',
    rating: '4.75',
    reviews: '800',
    icon: 'paw-outline',
    tint: '#FEF3C7',
    duration: '2–3 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Pet-safe products for fur & paw marks',
    badge: 'New',
    perks: ['Pet-safe', 'Fur vacuum', 'Floor mop'],
  },
  {
    id: 'senior',
    name: 'Senior-friendly Assist Clean',
    price: '₹349',
    rating: '4.74',
    reviews: '500',
    icon: 'heart-outline',
    tint: '#FEE2E2',
    duration: '2 hrs',
    location: 'Raipur',
    category: 'specialty',
    desc: 'Gentle clean with trained caring staff',
    perks: ['Gentle pace', 'Trusted staff', 'Bathroom help'],
  },
  {
    id: 'monthly',
    name: 'Monthly 8-Visit Plan',
    price: '₹999',
    rating: '4.83',
    reviews: '4k',
    icon: 'calendar-outline',
    tint: '#E6F4F2',
    duration: '8 visits/mo',
    location: 'Raipur',
    category: 'packages',
    desc: 'Twice-a-week regular clean subscription',
    badge: 'Best value',
    perks: ['Same maid', '8 visits', 'Save 15%'],
  },
];

export const FEATURED_SERVICES = HOME_SERVICES.slice(0, 3);
